/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GraphicDesignRouteImport } from './routes/graphic-design'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as PoliciesTermsRouteImport } from './routes/policies.terms'
import { Route as PoliciesRefundsRouteImport } from './routes/policies.refunds'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies.privacy'
import { Route as LocationsKentWaRouteImport } from './routes/locations.kent-wa'
import { Route as CareersScreeningRouteImport } from './routes/careers.screening'
import { Route as CareersAssessmentRouteImport } from './routes/careers.assessment'
import { Route as CareersApplyRouteImport } from './routes/careers.apply'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiScreeningSubmitRouteImport } from './routes/api.screening.submit'
import { Route as ApiScreeningStartRouteImport } from './routes/api.screening.start'
import { Route as ApiScreeningDecisionRouteImport } from './routes/api.screening.decision'
import { Route as ApiCareersUploadRouteImport } from './routes/api.careers.upload'
import { Route as ApiCareersApplyRouteImport } from './routes/api.careers.apply'
import { Route as ApiAssessmentSubmitRouteImport } from './routes/api.assessment.submit'
import { Route as ApiAssessmentStateRouteImport } from './routes/api.assessment.state'
import { Route as ApiAssessmentStartRouteImport } from './routes/api.assessment.start'
import { Route as ApiAssessmentSaveRouteImport } from './routes/api.assessment.save'
import { Route as ApiAssessmentRecordingUploadRouteImport } from './routes/api.assessment.recording-upload'

const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicDesignRoute = GraphicDesignRouteImport.update({
  id: '/graphic-design',
  path: '/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/policies/terms',
  path: '/policies/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRefundsRoute = PoliciesRefundsRouteImport.update({
  id: '/policies/refunds',
  path: '/policies/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsKentWaRoute = LocationsKentWaRouteImport.update({
  id: '/locations/kent-wa',
  path: '/locations/kent-wa',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersScreeningRoute = CareersScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => CareersRoute,
} as any)
const CareersAssessmentRoute = CareersAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => CareersRoute,
} as any)
const CareersApplyRoute = CareersApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CareersRoute,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreeningSubmitRoute = ApiScreeningSubmitRouteImport.update({
  id: '/api/screening/submit',
  path: '/api/screening/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreeningStartRoute = ApiScreeningStartRouteImport.update({
  id: '/api/screening/start',
  path: '/api/screening/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreeningDecisionRoute = ApiScreeningDecisionRouteImport.update({
  id: '/api/screening/decision',
  path: '/api/screening/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareersUploadRoute = ApiCareersUploadRouteImport.update({
  id: '/api/careers/upload',
  path: '/api/careers/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareersApplyRoute = ApiCareersApplyRouteImport.update({
  id: '/api/careers/apply',
  path: '/api/careers/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentSubmitRoute = ApiAssessmentSubmitRouteImport.update({
  id: '/api/assessment/submit',
  path: '/api/assessment/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentStateRoute = ApiAssessmentStateRouteImport.update({
  id: '/api/assessment/state',
  path: '/api/assessment/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentStartRoute = ApiAssessmentStartRouteImport.update({
  id: '/api/assessment/start',
  path: '/api/assessment/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentSaveRoute = ApiAssessmentSaveRouteImport.update({
  id: '/api/assessment/save',
  path: '/api/assessment/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentRecordingUploadRoute =
  ApiAssessmentRecordingUploadRouteImport.update({
    id: '/api/assessment/recording-upload',
    path: '/api/assessment/recording-upload',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/industries': typeof IndustriesRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/web-development': typeof WebDevelopmentRoute
  '/api/contact': typeof ApiContactRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/apply': typeof CareersApplyRoute
  '/careers/assessment': typeof CareersAssessmentRoute
  '/careers/screening': typeof CareersScreeningRoute
  '/locations/kent-wa': typeof LocationsKentWaRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/careers/': typeof CareersIndexRoute
  '/api/assessment/recording-upload': typeof ApiAssessmentRecordingUploadRoute
  '/api/assessment/save': typeof ApiAssessmentSaveRoute
  '/api/assessment/start': typeof ApiAssessmentStartRoute
  '/api/assessment/state': typeof ApiAssessmentStateRoute
  '/api/assessment/submit': typeof ApiAssessmentSubmitRoute
  '/api/careers/apply': typeof ApiCareersApplyRoute
  '/api/careers/upload': typeof ApiCareersUploadRoute
  '/api/screening/decision': typeof ApiScreeningDecisionRoute
  '/api/screening/start': typeof ApiScreeningStartRoute
  '/api/screening/submit': typeof ApiScreeningSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/industries': typeof IndustriesRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/web-development': typeof WebDevelopmentRoute
  '/api/contact': typeof ApiContactRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/apply': typeof CareersApplyRoute
  '/careers/assessment': typeof CareersAssessmentRoute
  '/careers/screening': typeof CareersScreeningRoute
  '/locations/kent-wa': typeof LocationsKentWaRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/careers': typeof CareersIndexRoute
  '/api/assessment/recording-upload': typeof ApiAssessmentRecordingUploadRoute
  '/api/assessment/save': typeof ApiAssessmentSaveRoute
  '/api/assessment/start': typeof ApiAssessmentStartRoute
  '/api/assessment/state': typeof ApiAssessmentStateRoute
  '/api/assessment/submit': typeof ApiAssessmentSubmitRoute
  '/api/careers/apply': typeof ApiCareersApplyRoute
  '/api/careers/upload': typeof ApiCareersUploadRoute
  '/api/screening/decision': typeof ApiScreeningDecisionRoute
  '/api/screening/start': typeof ApiScreeningStartRoute
  '/api/screening/submit': typeof ApiScreeningSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-automation': typeof AiAutomationRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/graphic-design': typeof GraphicDesignRoute
  '/industries': typeof IndustriesRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/web-development': typeof WebDevelopmentRoute
  '/api/contact': typeof ApiContactRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/apply': typeof CareersApplyRoute
  '/careers/assessment': typeof CareersAssessmentRoute
  '/careers/screening': typeof CareersScreeningRoute
  '/locations/kent-wa': typeof LocationsKentWaRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/careers/': typeof CareersIndexRoute
  '/api/assessment/recording-upload': typeof ApiAssessmentRecordingUploadRoute
  '/api/assessment/save': typeof ApiAssessmentSaveRoute
  '/api/assessment/start': typeof ApiAssessmentStartRoute
  '/api/assessment/state': typeof ApiAssessmentStateRoute
  '/api/assessment/submit': typeof ApiAssessmentSubmitRoute
  '/api/careers/apply': typeof ApiCareersApplyRoute
  '/api/careers/upload': typeof ApiCareersUploadRoute
  '/api/screening/decision': typeof ApiScreeningDecisionRoute
  '/api/screening/start': typeof ApiScreeningStartRoute
  '/api/screening/submit': typeof ApiScreeningSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-automation'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/graphic-design'
    | '/industries'
    | '/marketing'
    | '/portfolio'
    | '/services'
    | '/web-development'
    | '/api/contact'
    | '/careers/$slug'
    | '/careers/apply'
    | '/careers/assessment'
    | '/careers/screening'
    | '/locations/kent-wa'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/terms'
    | '/careers/'
    | '/api/assessment/recording-upload'
    | '/api/assessment/save'
    | '/api/assessment/start'
    | '/api/assessment/state'
    | '/api/assessment/submit'
    | '/api/careers/apply'
    | '/api/careers/upload'
    | '/api/screening/decision'
    | '/api/screening/start'
    | '/api/screening/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-automation'
    | '/blog'
    | '/contact'
    | '/graphic-design'
    | '/industries'
    | '/marketing'
    | '/portfolio'
    | '/services'
    | '/web-development'
    | '/api/contact'
    | '/careers/$slug'
    | '/careers/apply'
    | '/careers/assessment'
    | '/careers/screening'
    | '/locations/kent-wa'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/terms'
    | '/careers'
    | '/api/assessment/recording-upload'
    | '/api/assessment/save'
    | '/api/assessment/start'
    | '/api/assessment/state'
    | '/api/assessment/submit'
    | '/api/careers/apply'
    | '/api/careers/upload'
    | '/api/screening/decision'
    | '/api/screening/start'
    | '/api/screening/submit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-automation'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/graphic-design'
    | '/industries'
    | '/marketing'
    | '/portfolio'
    | '/services'
    | '/web-development'
    | '/api/contact'
    | '/careers/$slug'
    | '/careers/apply'
    | '/careers/assessment'
    | '/careers/screening'
    | '/locations/kent-wa'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/terms'
    | '/careers/'
    | '/api/assessment/recording-upload'
    | '/api/assessment/save'
    | '/api/assessment/start'
    | '/api/assessment/state'
    | '/api/assessment/submit'
    | '/api/careers/apply'
    | '/api/careers/upload'
    | '/api/screening/decision'
    | '/api/screening/start'
    | '/api/screening/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAutomationRoute: typeof AiAutomationRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  GraphicDesignRoute: typeof GraphicDesignRoute
  IndustriesRoute: typeof IndustriesRoute
  MarketingRoute: typeof MarketingRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
  ApiContactRoute: typeof ApiContactRoute
  LocationsKentWaRoute: typeof LocationsKentWaRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesRefundsRoute: typeof PoliciesRefundsRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
  ApiAssessmentRecordingUploadRoute: typeof ApiAssessmentRecordingUploadRoute
  ApiAssessmentSaveRoute: typeof ApiAssessmentSaveRoute
  ApiAssessmentStartRoute: typeof ApiAssessmentStartRoute
  ApiAssessmentStateRoute: typeof ApiAssessmentStateRoute
  ApiAssessmentSubmitRoute: typeof ApiAssessmentSubmitRoute
  ApiCareersApplyRoute: typeof ApiCareersApplyRoute
  ApiCareersUploadRoute: typeof ApiCareersUploadRoute
  ApiScreeningDecisionRoute: typeof ApiScreeningDecisionRoute
  ApiScreeningStartRoute: typeof ApiScreeningStartRoute
  ApiScreeningSubmitRoute: typeof ApiScreeningSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphic-design': {
      id: '/graphic-design'
      path: '/graphic-design'
      fullPath: '/graphic-design'
      preLoaderRoute: typeof GraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/policies/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/refunds': {
      id: '/policies/refunds'
      path: '/policies/refunds'
      fullPath: '/policies/refunds'
      preLoaderRoute: typeof PoliciesRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/kent-wa': {
      id: '/locations/kent-wa'
      path: '/locations/kent-wa'
      fullPath: '/locations/kent-wa'
      preLoaderRoute: typeof LocationsKentWaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/screening': {
      id: '/careers/screening'
      path: '/screening'
      fullPath: '/careers/screening'
      preLoaderRoute: typeof CareersScreeningRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/assessment': {
      id: '/careers/assessment'
      path: '/assessment'
      fullPath: '/careers/assessment'
      preLoaderRoute: typeof CareersAssessmentRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/apply': {
      id: '/careers/apply'
      path: '/apply'
      fullPath: '/careers/apply'
      preLoaderRoute: typeof CareersApplyRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screening/submit': {
      id: '/api/screening/submit'
      path: '/api/screening/submit'
      fullPath: '/api/screening/submit'
      preLoaderRoute: typeof ApiScreeningSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screening/start': {
      id: '/api/screening/start'
      path: '/api/screening/start'
      fullPath: '/api/screening/start'
      preLoaderRoute: typeof ApiScreeningStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screening/decision': {
      id: '/api/screening/decision'
      path: '/api/screening/decision'
      fullPath: '/api/screening/decision'
      preLoaderRoute: typeof ApiScreeningDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/careers/upload': {
      id: '/api/careers/upload'
      path: '/api/careers/upload'
      fullPath: '/api/careers/upload'
      preLoaderRoute: typeof ApiCareersUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/careers/apply': {
      id: '/api/careers/apply'
      path: '/api/careers/apply'
      fullPath: '/api/careers/apply'
      preLoaderRoute: typeof ApiCareersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment/submit': {
      id: '/api/assessment/submit'
      path: '/api/assessment/submit'
      fullPath: '/api/assessment/submit'
      preLoaderRoute: typeof ApiAssessmentSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment/state': {
      id: '/api/assessment/state'
      path: '/api/assessment/state'
      fullPath: '/api/assessment/state'
      preLoaderRoute: typeof ApiAssessmentStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment/start': {
      id: '/api/assessment/start'
      path: '/api/assessment/start'
      fullPath: '/api/assessment/start'
      preLoaderRoute: typeof ApiAssessmentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment/save': {
      id: '/api/assessment/save'
      path: '/api/assessment/save'
      fullPath: '/api/assessment/save'
      preLoaderRoute: typeof ApiAssessmentSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment/recording-upload': {
      id: '/api/assessment/recording-upload'
      path: '/api/assessment/recording-upload'
      fullPath: '/api/assessment/recording-upload'
      preLoaderRoute: typeof ApiAssessmentRecordingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CareersRouteChildren {
  CareersSlugRoute: typeof CareersSlugRoute
  CareersApplyRoute: typeof CareersApplyRoute
  CareersAssessmentRoute: typeof CareersAssessmentRoute
  CareersScreeningRoute: typeof CareersScreeningRoute
  CareersIndexRoute: typeof CareersIndexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSlugRoute: CareersSlugRoute,
  CareersApplyRoute: CareersApplyRoute,
  CareersAssessmentRoute: CareersAssessmentRoute,
  CareersScreeningRoute: CareersScreeningRoute,
  CareersIndexRoute: CareersIndexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAutomationRoute: AiAutomationRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  GraphicDesignRoute: GraphicDesignRoute,
  IndustriesRoute: IndustriesRoute,
  MarketingRoute: MarketingRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
  ApiContactRoute: ApiContactRoute,
  LocationsKentWaRoute: LocationsKentWaRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesRefundsRoute: PoliciesRefundsRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
  ApiAssessmentRecordingUploadRoute: ApiAssessmentRecordingUploadRoute,
  ApiAssessmentSaveRoute: ApiAssessmentSaveRoute,
  ApiAssessmentStartRoute: ApiAssessmentStartRoute,
  ApiAssessmentStateRoute: ApiAssessmentStateRoute,
  ApiAssessmentSubmitRoute: ApiAssessmentSubmitRoute,
  ApiCareersApplyRoute: ApiCareersApplyRoute,
  ApiCareersUploadRoute: ApiCareersUploadRoute,
  ApiScreeningDecisionRoute: ApiScreeningDecisionRoute,
  ApiScreeningStartRoute: ApiScreeningStartRoute,
  ApiScreeningSubmitRoute: ApiScreeningSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
